### PR TITLE
Add option to not trade at startup advice

### PR DESCRIPTION
**Pull request by MarcDiethelm**
When restarting the bot after, say, changes to to the indicator settings an order created at startup may not be desirable.
This also marks the startup advice as such.

### CODE REVIEW

**Comment by 5an1ty** [comment]
I'm just wondering, what is the scenario you are talking about? Why would you not want to align yourself with what your indicator is saying?

**Comment by MarcDiethelm** [comment]
I found that when restarting the app with new indicator settings while the market is volatile, the initial trading advice may sometimes clearly be not in the interest of the user. E.g. the indicator advises to buy while the price on the charts is plummeting. In this case it's preferable to start trading at the next indicator update. The algorithm will make bad trades and those that occur at startup can be prevented with this PR.

**Comment by 5an1ty** [comment]
I guess it indeed depends on what your goal is. I assume if you were already in the right position before the start it wouldn't matter anyway. I guess it doesn't do any harm as long as it's configurable. Can't merge this branch anymore by the way, there seems to be some kind of conflict. (Haven't looked into it yet)

**Comment by MarcDiethelm** [comment]
Fixed.

**Comment by MarcDiethelm** [comment]
Bump. This PR should be good to merge now. I merged `master` back into this branch and fixed the conflicts.

**Pull request merged**
